server:
  port: ${SERVER_PORT:8615}

spring:
  application:
    name: police-evidence-ordnance-management
  datasource:
    url: jdbc:mysql://${DB_HOST:127.0.0.1}:${DB_PORT:13316}/${DB_NAME:police_eom}?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true&useSSL=false
    username: ${DB_USER:eom}
    password: ${DB_PASSWORD:eompass}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      connection-timeout: 30000
      maximum-pool-size: 10
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework: INFO
